- name: Create a new Demo EC2 instance
  hosts: local
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-8c1be5f6
      keypair: DevOpsEval # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: # Add subnet ID
         assign_public_ip: yes
      register: ec2
