---
- hosts: Performline
  user : root
  become: yes
  tasks:
    - name: Install python
      yum: pkg=python state=installed update_cache=true
    - name: Installs Nginx web server
      yum: pkg=nginx state=installed update_cache=true
    - service:
        name: nginx
        state: started
    - copy:
        src: /Users/harmansingh/DevOpsEval/bin/eval-server.linux-x86_64
        dest: /home/ec2-user/
        mode: 0777
    - copy:
        src: /Users/harmansingh/nginx.con
        dest: /etc/nginx/nginx.conf
    - service:
        name: nginx
        state: restarted
    - name: add a new string at the end of the file
      lineinfile: dest=/etc/rc.d/rc.local
                regexp=''
                insertafter=EOF
                line='./home/ec2-user/eval-server.linux-x86_64'
    - name : reboot
      shell : reboot
