---
- hosts: Performline
  user : root
  become: yes
  tasks:
    - name: Install python
      yum: pkg=python state=installed update_cache=true
    - name: Installs Nginx web server
      yum: pkg=nginx state=installed update_cache=true
